pluginGroup = ua.com.pimenov
pluginName = Hot Reloader - Hot reloading for HTML, CSS, JS, and more
pluginRepositoryUrl = https://github.com/olton/hotreloader-idea-plugin
pluginVersion = 0.3.4

pluginSinceBuild = 251
pluginUntilBuild = 262.*
pluginVerifierIdeVersions = 2025.1, 2025.2, 2025.3, 2026.1, 2026.2

platformType = WS
platformVersion = 2026.1
platformDownloadSources = true

platformPlugins =
platformBundledPlugins =
platformBundledModules =

gradleVersion = 9.0.0

kotlin.stdlib.default.dependency = false
kotlin.code.style=official

org.gradle.configuration-cache = true
org.gradle.caching = true

